---
dependencies:
  - role: katello
  - role: libvirt
    libvirt_tftp: true
  - role: katello_provisioning
    katello_provisioning_installer_options: "{{ luna_provisioning_installer_options }} + {{ luna_provisioning_installer_internal_options }}"
  - role: 'plugins/foreman_ansible/seed'
  # use role instead of installer options for openscap to install theforeman-foreman_scap_client puppet module
  - role: 'plugins/foreman_openscap/install'
  - role: 'plugins/foreman_openscap/seed'
    foreman_openscap_proxy: "{{ ansible_fqdn }}"
    foreman_openscap_ansible_proxy: "{{ ansible_fqdn }}"
    foreman_openscap_puppet_proxy: "{{ ansible_fqdn }}"
    foreman_openscap_hostgroup_parent: "Katello CentOS 7"
  - role: 'plugins/foreman_templates/seed'
