---
# testing both --name and --title for backward compatibility
- name: 'create CentOS 7'
  shell: >
    {{ foreman_provisioning_hammer }} os info --name "CentOS 7" ||
    {{ foreman_provisioning_hammer }} os info --title "CentOS 7" ||
    {{ foreman_provisioning_hammer }} os create
    --name CentOS --major 7 --architectures x86_64 --family 'Redhat' --media 'CentOS mirror' --partition-tables 'Kickstart default'

- name: 'find CentOS 7'
  shell: >
    {{ foreman_provisioning_hammer }} --output json os info --name "CentOS 7" ||
    {{ foreman_provisioning_hammer }} --output json os info --title "CentOS 7"
  register: foreman_provisioning_centos73_json
  ignore_errors: True

- name: 'get CentOS 7 info'
  set_fact:
    foreman_provisioning_centos73: "{{ foreman_provisioning_centos73_json.stdout|from_json }}"

- name: 'find kickstart templates'
  shell: >
    {{ foreman_provisioning_hammer }} --output=json template list
    --search 'name ~ "Kickstart default"'
  register: kickstart_templates_json

- name: 'set kickstart templates'
  set_fact:
    kickstart_templates: "{{ kickstart_templates_json.stdout|from_json }}"

- name: 'associate kickstart templates to CentOS 7'
  shell: >
    {{ foreman_provisioning_hammer }} template add-operatingsystem --id {{ item.Id }} --operatingsystem 'CentOS 7'
  with_items: "{{ kickstart_templates }}"

- name: 'set default templates for CentOS 7'
  shell: >
    {{ foreman_provisioning_hammer }} os set-default-template --id {{ foreman_provisioning_centos73.Id }} --config-template-id {{ item.Id }}
  with_items: "{{ kickstart_templates }}"

- name: 'set unattended_url'
  shell: >
    {{ foreman_provisioning_hammer }} settings set --name unattended_url --value 'http://{{ foreman_provisioning_ip_address }}'

- name: 'find hostgroup Forklift Base'
  shell: >
    {{ foreman_provisioning_hammer }} hostgroup info --name 'Forklift Base'
  register: foreman_provisioning_hostgroup_base
  ignore_errors: True

- name: 'create hostgroup Forklift Base'
  shell: >
    {{ foreman_provisioning_hammer }} hostgroup create
    --name 'Forklift Base'
    --architecture x86_64
    --domain {{ foreman_provisioning_domain }}
    --environment production
    --puppet-ca-proxy-id {{ foreman_provisioning_smart_proxy.Id }}
    --puppet-proxy-id {{ foreman_provisioning_smart_proxy.Id }}
    --subnet '{{ foreman_provisioning_network }}/24'
    --root-pass changeme
    {{ foreman_provisioning_hammer_taxonomy_params }}
  when: foreman_provisioning_hostgroup_base.stderr.find('not found') != -1

- name: 'find hostgroup Forklift CentOS 7'
  shell: >
    {{ foreman_provisioning_hammer }} hostgroup info --name 'Forklift CentOS 7 Mirror'
  register: foreman_provisioning_hostgroup_centos_mirror
  ignore_errors: True

- name: 'create hostgroup Forklift CentOS 7 Mirror'
  shell: >
    {{ foreman_provisioning_hammer }} hostgroup create
    --name 'Forklift CentOS 7 Mirror'
    --operatingsystem 'CentOS 7'
    --medium 'CentOS mirror'
    --partition-table 'Kickstart default'
    --parent 'Forklift Base'
    {{ foreman_provisioning_hammer_taxonomy_params }}
  when: foreman_provisioning_hostgroup_centos_mirror.stderr.find('not found') != -1
