---
- name: 'Setup Epel Repository'
  yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: "{{ epel_repositories_state }}"
  tags:
    - packages
  when: ansible_os_family == 'RedHat'
